// Code generated by protoc-gen-go. DO NOT EDIT.
// source: canvas.proto

package avvaproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Canvas struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Enabled              bool     `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Canvas) Reset()         { *m = Canvas{} }
func (m *Canvas) String() string { return proto.CompactTextString(m) }
func (*Canvas) ProtoMessage()    {}
func (*Canvas) Descriptor() ([]byte, []int) {
	return fileDescriptor_canvas_1f9121300ebd1ee2, []int{0}
}
func (m *Canvas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Canvas.Unmarshal(m, b)
}
func (m *Canvas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Canvas.Marshal(b, m, deterministic)
}
func (dst *Canvas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Canvas.Merge(dst, src)
}
func (m *Canvas) XXX_Size() int {
	return xxx_messageInfo_Canvas.Size(m)
}
func (m *Canvas) XXX_DiscardUnknown() {
	xxx_messageInfo_Canvas.DiscardUnknown(m)
}

var xxx_messageInfo_Canvas proto.InternalMessageInfo

func (m *Canvas) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Canvas) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func init() {
	proto.RegisterType((*Canvas)(nil), "avvaproto.Canvas")
}

func init() { proto.RegisterFile("canvas.proto", fileDescriptor_canvas_1f9121300ebd1ee2) }

var fileDescriptor_canvas_1f9121300ebd1ee2 = []byte{
	// 93 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x4e, 0xcc, 0x2b,
	0x4b, 0x2c, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4c, 0x2c, 0x2b, 0x4b, 0x04, 0x33,
	0x95, 0x8c, 0xb8, 0xd8, 0x9c, 0xc1, 0x52, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0xac, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x12, 0x5c, 0xec, 0xa9, 0x79, 0x89, 0x49, 0x39,
	0xa9, 0x29, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x30, 0x6e, 0x12, 0x1b, 0x58, 0xab, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x80, 0xff, 0x90, 0x4c, 0x55, 0x00, 0x00, 0x00,
}
